### ISSUE TITLE
Bug: TypeError: selectionsAPI.isModal is not a function

### ISSUE THREAD

**Issue by LiKang6688** [qlik-oss/sn-table#107]
run the sn-table in sense-client:
<img width="664" alt="Screenshot 2021-02-21 at 21 14 02" src="https://user-images.githubusercontent.com/4471489/108637193-e5392080-7489-11eb-9e02-e883360ca04d.png">

**Comment by haxxmaxx** [comment]
This has been added to sense-cliient
