### ISSUE TITLE
[Question] - Difference between on-the-fly vs. embedded table

### ISSUE THREAD

**Issue by zangerls** [qlik-oss/sn-table#1078]
Hi everyone

Can anyone tell me why embedded tables use pagination above 100 rows while a table created on-the-fly has no issues displaying >1m rows? Intuitively, I see no (technical) reason how/why these two differ.

Thanks for any help/explanations!

**Comment by haxxmaxx** [comment]
Hi, sorry we completely missed this issue.

There is a property controlling whether to render the table paginated or not. It is called `usePagination`, see the API https://qlik.dev/apis/javascript/sn-table/. That should be false by default. So unless it is specifically set for some reason, the table should render non-paginated. 

We also changed the default behaviour a while back, so make sure that you are using the latest version of sn-table.

If it still renders paginated, that might be a bug
