### ISSUE TITLE
When using NVDA screenreader it is not possible to move with arrow keys in the number of rows drop-down, until you press enter again

### ISSUE THREAD

**Issue by mlb76** [qlik-oss/sn-table#166]
When using NVDA screenreader it is not possible to move with arrow keys in the number of rows drop-down. You can tab to the drop-down and open it, but you can not move between the options in the drop down. This is only an issue when using the NVDA screen reader in the table mashup.

**Comment by haxxmaxx** [comment]
https://github.com/mui-org/material-ui/issues/26033 This is an issue on MUIs own documentation page, so put a bug on them. There is a work-around: just pressing space/enter one more time and the arrows work. That will have to do for now.
