### ISSUE TITLE
Sort buttons incorrectly labeled

### ISSUE THREAD

**Issue by anoQlik** [qlik-oss/sn-table#216]
Add screen reader only text or an aria-label attribute to each of these buttons which tells users where they go and/or what they do. These are labeled with title attributes, but this is not sufficient for these labels to be ready consistently across various browser and screen reader combinations.

**Comment by haxxmaxx** [comment]
First off, we need to have both listeners (keyboard and mouse) on the `<th>` cell, and mark it as a button.
Then we need to use `aria-sort` to tell which order it is sorted.
Then there needs to be a hidden label (not aria-label) with instructions. what does the button do? `press to sort ascending/descending` or similar
