### ISSUE TITLE
US: Support sense themes

### ISSUE THREAD

**Issue by Caele** [qlik-oss/sn-table#221]
Add support for sense theming similar to the native table.

Straight table supported properties:
```
"straightTable": {
	"header": {
		"fontSize": "@H4",
		"color": "@B35"
	},
	"content": {
		"fontSize": "@H4",
		"color": "@B35",
		"hover": {
			"backgroundColor": "inherit",
			"color": "inherit"
		}
	}
},
```
Note: target name needs to be "straightTable" to ensure backwards compatibility, but should consider how we can update it.

**Comment by LiKang6688** [comment]
"straightTable": {
      "backgroundColor": "@light",
      "title": {
        "main": {
          "color": "@default",
          "fontSize": "@font-normal",
          "fontFamily": "@font-family"
        },
        "subTitle": {
          "color": "@default",
          "fontSize": "@font-normal",
          "fontFamily": "@font-family"
        },
        "footer": {
          "color": "@default",
          "fontSize": "@font-normal",
          "fontFamily": "@font-family",
          "backgroundColor": "@light"
        }
      },
      "header": {
        "fontSize": "@font-normal",
        "fontFamily": "@font-family",
        "color": "@default"
      },
      "content": {
        "fontSize": "@font-normal",
        "fontFamily": "@font-family",
        "color": "@default"
      }
    },

**Comment by LiKang6688** [comment]
#455  When the table background color from the sense theme is transparent, there is a header background color depending on the header font color to avoid seeing the table body through the table head.

#459 When you set the color of header content, the color of the sort label should be the same as that.
          When there is no header content color setting, the sort label color is kind of white in the dark background color and black in the light background color.

#446 Adjust the TablePagination font color based on the background color

#451 There is the border color depending on the background color

#453 Apply the body content hover background color and color from the theme
