### ISSUE TITLE
Select constraint should be handled

### ISSUE THREAD

**Issue by niekvanstaveren** [qlik-oss/sn-table#241]
When embedding the sn-table you can set constraints as input. The select constraint should block making selections inside the object, but currently it does not.

See https://qlik.dev/libraries-and-tools/nebulajs/configuration#constraints

**Comment by LiKang6688** [comment]
There are three different constraints you can apply:

passive: turn off interactions like tooltips.
active: turn off interactions that affect the state of the visual representation like zoom, scroll, etc.
select: turn off selections.
{
  context: {
    constraints: {
      active: true,
      passive: true,
      select: true,
    },
  },
};
