### ISSUE TITLE
Pagination should auto-hide or with option in properties

### ISSUE THREAD

**Issue by marvelvv** [qlik-oss/sn-table#302]
Pagination should auto-hide when not needed, and have an option/property.

![image](https://user-images.githubusercontent.com/47638667/135863964-f02859ad-4052-48e5-a95f-440b9cb70769.png)

**Comment by haxxmaxx** [comment]
Cool our first externally reported issues!
We are currently wrapping up a batch of work, should be done within a couple of weeks, then we can take a look at this.
