### ISSUE TITLE
Refactoring code to apply the useContext and useReducer hooks together

### ISSUE THREAD

**Issue by LiKang6688** [qlik-oss/sn-table#357]

**Comment by a-m-dev** [comment]
we have agreed to hold this task for now

**Comment by haxxmaxx** [comment]
I've concluded that there is no simple way of doing this. Redux would have been perfect for this, except it does not support storing non-serialized values (e.g. functions, we want to put APIs in there). And useContext doesn't have the same features we need, and hard to initialize in the way I want to, AFAIK. This is not worth investing more time in, unless someone has a solution that is guaranteed to work. We will have to live with some prop drilling and large amounts of arguments passed to util functions for now.
