### ISSUE TITLE
Some styling issues in agnostic table.

### ISSUE THREAD

**Issue by mlb76** [qlik-oss/sn-table#37]
Some styling issues in agnostic table.

1. Checkmark in drop down is almost overlapping the number.  
2. Arrow dropdown for selecting rows per page is too close the the line of the dropdown square
3. The height of the dropdown also does not look proportional to the content of it.

![agt, drop-down](https://user-images.githubusercontent.com/29750277/104337900-3f8faa80-54f6-11eb-83d7-018a5ef08a21.jpg)
![agt, drop-down2](https://user-images.githubusercontent.com/29750277/104337903-40284100-54f6-11eb-843d-06db2ea27287.jpg)

**Comment by haxxmaxx** [comment]
I think these styling issues are more than just styling, causing some react issues and thus scrolling not working when imported to sense.
