### ISSUE TITLE
Styling of the pagination actions component is different in nebula and sense

### ISSUE THREAD

**Issue by eliseeborn** [qlik-oss/sn-table#372]
When the component looks aligned with the rest of the footer in sense, it looks like this in nebula:
![Screenshot 2021-10-29 at 09 24 41](https://user-images.githubusercontent.com/26596242/139393398-f8f21534-3bd8-475b-b112-f87df42e1513.png)
ie. the label for the dropdown is slightly higher than the text in the dropdown and the pagination buttons, and the whole component is higher than the rest of the footer.
Probably due to some css present in sense that affects the component.

**Comment by haxxmaxx** [comment]
Should add that it looks fine in a mashup, so it seems like it's only in the dev env 
<img width="755" alt="Screenshot 2021-11-04 at 18 32 59" src="https://user-images.githubusercontent.com/9249820/140390148-4798318c-650b-4871-b886-bcf9c797f74b.png">

**Comment by haxxmaxx** [comment]
Since it looks fine when actually used outside the dev environment, and we will revisit the UX of the pagination I am closing this
