### ISSUE TITLE
changing page size of large table locks page

### ISSUE THREAD

**Issue by chadmoore** [qlik-oss/sn-table#486]
Attempting to change the page size of a table with millions of rows locks the page completely.

**Comment by chadmoore** [comment]
Actually, I need to revise that ... if I load the mashup with selections made to keep the row count around 1m, I can change page size with ~1m delay, but if I leave selections cleared (5m+ rows) it seems to lock indefinitely

**Comment by chadmoore** [comment]
It wasn't indefinite. Changing a table w/ 5,724,279 rows from 100 rows per page to 10 rows per page took 43m55s

**Comment by haxxmaxx** [comment]
Thanks for taking the time to investigating this. The paging is suppose to minimize delays like this singe we would maximally deal with 100 rows at a time, so this should defenetly not be the case, we will look into it

**Comment by haxxmaxx** [comment]
This should be fixed in v2.1.0. Now the default way of loading data using virtualization. You can still use the pagination, and that performance should be better as well. New documentation here: https://qlik.dev/embed/visualizations-to-embed/table/sn-table
