### ISSUE TITLE
removing selections from a mashup with a table containing a high number of rows shows significant delay

### ISSUE THREAD

**Issue by chadmoore** [qlik-oss/sn-table#487]
attempting to remove selections using the nebula selection bar when a mashup page contains a table with millions of rows locks the ui for 20+ seconds

**Comment by chadmoore** [comment]
This problem is unfortunately not fixed in v1.9.0

**Comment by haxxmaxx** [comment]
Are you clearing the selections or canceling them (the x button)? In any case that is way too long
