### ISSUE TITLE
Exporting data from the Table directly

### ISSUE THREAD

**Issue by leesmith084** [qlik-oss/sn-table#725]
Hi There, i have started to use nebula and in particular the sn-table... 

does this have any features that would allow the customer to download the data from the table direct to excel? 

im thinking a couple of options, whats in view (e.g 100 rows visible, all data up to a certain volume). do you happen to know if this is possible?

thanks

**Comment by haxxmaxx** [comment]
If you are using it inside Qlik Sense there is that option. If you are using it in a mashup that feature is not available. There are no current plans of implementing outside sense.
