### ISSUE TITLE
Build: Fix incompatability with node-resolve 14

### ISSUE THREAD

**Issue by Caele** [qlik-oss/sn-table#750]
The nebula.js/cli-build version 3.0.4 includes a dependecy update of @rollup/plugin-node-resolve to v14 (but 15 has the same issue). This somehow breaks the table in particular, and stops it from working properly

The Nebula PR is this: https://github.com/qlik-oss/nebula.js/pull/946
The change in @rollup/plugin-node-resolve is https://github.com/rollup/plugins/pull/1245

The actual error:

---> BUILDING SUPERNOVA
No name was provided for external module “stream” in “output.globals” – guessing “require$$7$1”.
Creating a browser bundle that depends on Node.js built-in modules (“stream”). You might need to include https://github.com/FredKSchott/rollup-plugin-polyfill-node

Early googling suggests that it could be a problem with the typescript plugin or config, but no luck yet.

**Comment by haxxmaxx** [comment]
what happened to this one? seems like nebula is not using v14 at all anymore?

**Comment by haxxmaxx** [comment]
we are way passed version 3.0.4 of `cli-build`. Closing this
