### ISSUE TITLE
US: Type definition for nebula.js/sn-table

### ISSUE THREAD

**Issue by erYasar** [qlik-oss/sn-table#779]
Could you help me with the Type definition for nebula.js/sn-table.

error TS7016: Could not find a declaration file for module '@nebula.js/sn-bar-chart'. './node_modules/@nebula.js/sn-bar-chart/dist/sn-table.js' implicitly has an 'any' type.
Try npm i --save-dev @types/nebula.js__sn-table if it exists or add a new declaration (.d.ts) file containing declare module '@nebula.js/sn-table';

**Comment by haxxmaxx** [comment]
That error looks a bit strange to me. It looks like you have sn-table code inside a sn-bar-chart? Are you building a mashup with both a sn-bar-chart and sn-table? My guess is that the sn-table code ended up in the sn-bar-charts node_modules for some reason

**Comment by haxxmaxx** [comment]
Closing this since I got no response
