### ISSUE TITLE
US:  Documentation on how to use sn-table v2

### ISSUE THREAD

**Issue by jackBrioschi** [qlik-oss/sn-table#942]
On Demand Table not rendered with the 2.0.0 version. 
I tried to revert back to the previous version (1.25.0) and the code is working fine and table is rendered correctly. 
While with the new 2.0.0 version is not working anymore. Documentation on how to use it seems to be identical from 1.25.0 to 2.0.0.

<img width="876" alt="nebula_table_changes" src="https://user-images.githubusercontent.com/61158347/227203826-5ebdf29e-9e48-4093-b3bb-ad8c4f437a05.PNG">

**Comment by LiKang6688** [comment]
@jackBrioschi Thank you for checking. The documentation for sn-table v2  was updated recently. https://qlik.dev/embed/visualizations-to-embed/table/sn-table
Please let us know if your question is answered.

**Comment by jackBrioschi** [comment]
thanks for answering, 
I see that the table now is working.
Have a great day!
Giacomo
