### ISSUE TITLE
Yarn build fails with 401 Unauthorized

### ISSUE THREAD

**Issue by erikwett** [qlik-oss/sn-table#979]
When I try to build an extension, yarn gives the following error:
error An unexpected error occurred: "https://npm.pkg.github.com/download/@qlik-trial/sprout/2.45.6/f62fa8066cf7ac6ddb3b1f0f1e3cdd65933d060a: Request failed \"401 Unauthorized\"".

Something missing in my setup??

[yarn-error.log](https://github.com/qlik-oss/sn-table/files/11198898/yarn-error.log)

**Comment by thomaspessato** [comment]
This is still happening.

I cannot even download the extension, since I could not find any builds for it (zip file).

What I was doing is cloning and building. that way I could upload it to my Qlik environment. now there's no way to do it.

**Comment by thomaspessato** [comment]
Thank you @haxxmaxx 

I ended up deleting the sprout package from everywhere and replaced with a simple <div> with a - and + chars to make it build and not break everything.

I also saw that this happens to the sn-pivot-table as well, so I did it on that repo too.

**Comment by haxxmaxx** [comment]
ok good that you found a work-around. We'll keep this issue open until the everyone can run a build the sn-table

**Comment by jeff-1984** [comment]
Hello, is there any chance that the @qlik-trial/sprout dependency become public ? 

I see there is a lot of usage of these objects in the project, did you replace them by something else @thomaspessato ?

Ex: in HeadCellMenu.tsx

Is that just icons ?

Thanks,
JF

**Comment by haxxmaxx** [comment]
HI,

Unfortunately I don't have any news about when and if sprout will become public. However there are onging discussions about how we should treat this issue. This code being open-source but not possible to run, doesn't really make sense. I will update here when there are any news.

**Comment by thomaspessato** [comment]
@jeff-1984 I deleted it, they're just icons
